version: "3.8"

services:

  #Nginx server
  websrv:
    build:
      context: ./conf/nginx
      args:
        user: totoro
        uid: 1000
    container_name: myWeb
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/projects:/home/totoro/projects"

  # PHP server
  phpsrv:
    build:
      context: ./conf/php
      args:
        user: totoro
        uid: 1000
    container_name: myPhp
    restart: unless-stopped
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "~/projects:/home/totoro/projects"

  # Go server
  gosrv:
    build:
      context: ./conf/golang
      args:
        user: totoro
        uid: 1000
    container_name: myGolang
    restart: unless-stopped
    tty: true
    ports:
      - "8282:8080"
    volumes:
      - "~/projects:/home/totoro/projects"

  # PostgresSQL server
  postgressrv:
    build:
      context: ./conf/postgres
    container_name: myPostgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    tty: true
    volumes:
      - "pgsqlvol:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_PASSWORD: g0dmode
      PGDATA: /var/lib/postgresql/data

  # PgAdmin4
  pgadminsrv:
    image: dpage/pgadmin4:8.3
    container_name: myPgadmin
    restart: unless-stopped
    ports:
      - "8181:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: totoro1302@pgadmin.test
      PGADMIN_DEFAULT_PASSWORD: topsecret

  #Grafana
  grafanasrv:
    image: grafana/grafana:10.3.3
    container_name: myGrafana
    ports:
      - "3000:3000"

  #Loki
  lokisrv:
    build:
      context: ./conf/loki
    container_name: myLoki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  #Promtail
  promtail:
    image: grafana/promtail:latest
    container_name: myPromtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf/promtail/conf.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - lokisrv

volumes:
  pgsqlvol:
