version: "3.7"

services:

  #Nginx server
  websrv:
    build:
      context: ./conf/nginx
      args:
        user: totoro
        uid: 1000
    container_name: myWeb
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/projects:/home/totoro/projects"

  # PHP server
  phpsrv:
    build:
      context: ./conf/php
      args:
        user: totoro
        uid: 1000
    container_name: myPhp
    restart: unless-stopped
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "~/projects:/home/totoro/projects"

  # Go server
  gosrv:
    build:
      context: ./conf/golang
      args:
        user: totoro
        uid: 1000
    container_name: myGolang
    restart: unless-stopped
    tty: true
    security_opt:
      - "seccomp:unconfined"
    ports:
      - "40000:40000"
    volumes:
      - "~/projects:/home/totoro/projects"

  # MariaDb server
  # mariadbsrv:
  #   image: mariadb:10.11
  #   container_name: myMariaDb
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306"
  #   tty: true
  #   volumes:
  #     - "mariadbvol:/var/lib/mysql"
  #   environment:
  #     MARIADB_ROOT_PASSWORD: g0dmode

  # PostgresSQL server
  postgressrv:
    build:
      context: ./conf/postgres
    container_name: MyPostgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    tty: true
    volumes:
      - "pgsqlvol:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_PASSWORD: g0dmode
      PGDATA: /var/lib/postgresql/data

  #Redis server
  redissrv:
    image: redis:6.0
    container_name: myRedis
    restart: unless-stopped

volumes:
  pgsqlvol:
